# Use a Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the producer script into the container
COPY producer.py .

# Install dependencies (kafka-python library)
RUN pip install kafka-python

# Set the default command to run the producer script
CMD ["python", "producer.py"]
